# Generated by Django 5.1.2 on 2024-10-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('it_staff', 'IT Staff'), ('ceso_staff', 'CESO Staff'), ('employee', 'Employee'), ('student', 'Student')], max_length=20),
        ),
    ]
